// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RealEstate.Shared
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class RealEstateLead : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""RealEstateLead"",""namespace"":""RealEstate.Shared"",""fields"":[{""name"":""LeadId"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Address"",""type"":""string""},{""name"":""LeadType"",""type"":{""type"":""enum"",""name"":""LeadType"",""namespace"":""RealEstate.Shared"",""symbols"":[""Rent"",""Buy""]}},{""name"":""RealEstateType"",""type"":{""type"":""enum"",""name"":""RealEstateType"",""namespace"":""RealEstate.Shared"",""symbols"":[""House"",""Apartment"",""Land""]}},{""name"":""Price"",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":18,""scale"":2}}]}");
		private System.Guid _LeadId;
		private string _Address;
		private RealEstate.Shared.LeadType _LeadType;
		private RealEstate.Shared.RealEstateType _RealEstateType;
		private Avro.AvroDecimal _Price;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return RealEstateLead._SCHEMA;
			}
		}
		public System.Guid LeadId
		{
			get
			{
				return this._LeadId;
			}
			set
			{
				this._LeadId = value;
			}
		}
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				this._Address = value;
			}
		}
		public RealEstate.Shared.LeadType LeadType
		{
			get
			{
				return this._LeadType;
			}
			set
			{
				this._LeadType = value;
			}
		}
		public RealEstate.Shared.RealEstateType RealEstateType
		{
			get
			{
				return this._RealEstateType;
			}
			set
			{
				this._RealEstateType = value;
			}
		}
		public Avro.AvroDecimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				this._Price = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.LeadId;
			case 1: return this.Address;
			case 2: return this.LeadType;
			case 3: return this.RealEstateType;
			case 4: return this.Price;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.LeadId = (System.Guid)fieldValue; break;
			case 1: this.Address = (System.String)fieldValue; break;
			case 2: this.LeadType = (RealEstate.Shared.LeadType)fieldValue; break;
			case 3: this.RealEstateType = (RealEstate.Shared.RealEstateType)fieldValue; break;
			case 4: this.Price = (Avro.AvroDecimal)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
